### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by arcanjl** [napolitanod/Danger-Zone#108]
What happened to your training videos? I would love to use this, but have no clue :)

**Comment by napolitanod** [comment]
Hmm, looks like they are gone. They must have been associated to my other developer account that I deleted. They were likely out dated anyway. I'll try to get one up quickly if I don't botch it.

**Comment by napolitanod** [comment]
I added an intro video that covers the basics (https://youtu.be/QO1DytuxN3A). First half walks through the basics and second half covers configuration settings and some additional tricks like setting a zone's dimensions equal to a regions.

I'll try to get some other videos up, but difficulty has been time and finding a quiet place to do it.

**Comment by arcanjl** [comment]
That is awesome! Thank you so much! If you have time, could you make one for one of a jb2a trap? :) 
For now, I will dig in, again, thank you!
