### ISSUE TITLE
Import/Export Feature

### ISSUE THREAD

**Issue by brunocalado** [napolitanod/Danger-Zone#11]
Hi.

Can you add an import/export feature for the dangers?

![image](https://user-images.githubusercontent.com/4999783/134948964-d9fe03a4-7e38-49c1-8e91-14e9db20fd11.png)

Thank you.

**Comment by brunocalado** [comment]
Oh, sorry. Yes. It's working.

Tks

**Comment by napolitanod** [comment]
Thanks-is it the system that is affecting the form or a module? I can put a patch in if I know what to test against.

Thanks!!!

**Comment by brunocalado** [comment]
No. I'm just a noob. lol

I'm trying to integrate with sequencer ship.


https://user-images.githubusercontent.com/4999783/134961772-b5a3d2f7-a695-42af-858b-6edb8890d1e9.mp4
