### ISSUE TITLE
No Icons despite following tutorial, impossible to trigger Danger Zone

### ISSUE THREAD

**Issue by rtschaefer** [napolitanod/Danger-Zone#111]
None of the icons appear, so I am completely unable to trigger a danger zone. None of the icon features appear, even when the settings are configured to do so. I have burned way too much time on this with nothing to show for it. 100s of modules in use and four years experience in Foundry and this is the one and only module that I cannot get to work.  I am on version 12, stable Build 331, using D&D 3.3.1.   Unless action is taken quickly to remedy the broken module, I am deleting it, which is a shame, because I would be keen to put it to use.

**Comment by napolitanod** [comment]
Please remove the module and don't post here again. This is a free module, I'm not your servant, and I don't talk to people who talk to me like you are.
