### ISSUE TITLE
Danger Zone Manual Trigger not displaying.

### ISSUE THREAD

**Issue by Lexi-dog** [napolitanod/Danger-Zone#119]
I'm having an issue similar to an earlier, ruder issue. I can not find a way to have the danger zone manual trigger button display. I've tried moving it to the navigation bar and macro bar in the settings without luck.  I have also tried disabling Monk's Navigation and Macro bar extender without any luck. Is there any additional information I could provide to help narrow down the issue?

**Comment by napolitanod** [comment]
Hi! I should create an FAQ for this given that this info is spread out over the site/wiki and so I imagine not super obvious. Here's a comprehensive list. Let me know if none of these are the cause and, if so, what system you are on:

There are a few things that will prevent the Danger Zone buttons from displaying:

- The scene that you want to see the buttons on must be activated.
- The scene that you want to see the buttons on must be gridded.
- If the zone is triggered by a manual event, the zone must be 'Active' (see the zone's Basics tab). Note, zones with other events will display on the page and the button can be used to toggle them active or inactive.
- The buttons must be configured to where you want them displayed. See 'Zone Trigger Display Location' in the Danger Zone Configuration Game Settings. The default is to display the buttons next to the scene name in the scene navigation (where lists of scenes are shown at top of scene on the canvas). This can be toggled to display to right of the macro bar instead in the settings.
- A different module cannot be interfering / customizing the html in the chosen area. I have encountered in the past some modules that modify the chosen area (scene nav or macro hotbar), causing the buttons to not display. If you have other modules enabled, please check if this is still an issue with all modules except Danger Zone disabled. A quick way to do this if you don't want to disable all modules in the current world is to create a new world, only enable Danger Zone, add a blank scene, add a simple danger and then manual triggered zone to the scene, and see if button shows in scene nav or macro hotbar.

**Comment by Lexi-dog** [comment]
Entirely my fault. In all the documentation I was not noticing the part where the scene needed to be Active, and not just viewed. 

Thank you so much for the response! Have a wonderful rest of your day.
