### ISSUE TITLE
Cannot Draw a Zone

### ISSUE THREAD

**Issue by Armandeus66** [napolitanod/Danger-Zone#62]
I can't seem to draw a zone using the crosshair icon. Is there a module known to conflict with this function? Do I have to be in a certain mode (tile, drawing, wall, etc.) to use it?

Also, is there a Discord server where we can ask questions about how to set up a zone? I have a really simple thing I want to do but can't seem to figure out.

**Comment by napolitanod** [comment]
Good afternoon,

There may be another module (or game system) interfering though I am not aware of one. When you have the zone form open and select the crosshairs this should minimize the form and offer you a prompt to select one grid square and then a second, which sets the boundary of the zone.

**Comment by napolitanod** [comment]
Oh, and you can add questions here that the wiki doesn't answer. There's some help videos also. The main Foundry VTT discord module troubleshooting can be helpful in some cases if somebody is on that has used the module. I may at some point get a discord but I don't have enough modules of my own to sustain a dedicated server.

**Comment by Armandeus66** [comment]
Hi. I don't get the prompt and the form isn't minimized.
Discord servers are free. Even I have one, and I have no modules or anything. I just use it to talk with friends.
I tried asking on the Foundry Discord but no-one could answer.

**Comment by napolitanod** [comment]
If you disable all modules and are still having an issue please let me know what version of foundry you are on, version of Danger Zone, and what game system

**Comment by CatbotTsumi** [comment]
The Select Grid Dimensions button is 'disabled' for me too.

**Comment by napolitanod** [comment]
Can you please provide the following info:
- Is this occurring on a gridless map? Gridless maps are not currently supported:
- Foundry version:
- Danger Zone version:
- Game system (e.g. dnd5e):
- Does this occur when all other modules are disabled?
Thank you!

**Comment by napolitanod** [comment]
With the recent push 1.6.8.1 if have added message to the form to indicate why the location picker would be disabled (if it is). It is disabled for gridless maps or on inactive scenes. Likely the issue is that the scene is gridless or needs to be activated. If that isn't the case, please provide the details previously requested.
